force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Companies Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Drivers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Driver__c/fields/Companies__c.field-meta.xml
<CustomField>
    <fullName>Companies__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Companies</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>Drivers</relationshipLabel>
    <relationshipName>Drivers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transportation__c/Transportation__c.object-meta.xml
<CustomObject>
    <label>Transportation</label>
    <nameField>
        <label>Transportation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transportations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transportation__c/fields/Companies__c.field-meta.xml
<CustomField>
    <fullName>Companies__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Companies</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>Transportations</relationshipLabel>
    <relationshipName>Transportations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transportation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transportations</relationshipLabel>
    <relationshipName>Transportations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transportation__c/fields/Destination_Pick_on_Map__c.field-meta.xml
<CustomField>
    <fullName>Destination_Pick_on_Map__c</fullName>
    <label>Destination (Pick on Map)</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transportation__c/fields/Drivers__c.field-meta.xml
<CustomField>
    <fullName>Drivers__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Drivers</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Transportations</relationshipLabel>
    <relationshipName>Transportations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transportation__c/fields/Starting_Point_Pick_on_Map__c.field-meta.xml
<CustomField>
    <fullName>Starting_Point_Pick_on_Map__c</fullName>
    <label>Starting Point (Pick on Map)</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transportation__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>recieved</fullName>
                <default>true</default>
                <label>recieved</label>
            </value>
            <value>
                <fullName>processing</fullName>
            </value>
            <value>
                <fullName>delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transportation__c/fields/Type_of_product__c.field-meta.xml
<CustomField>
    <fullName>Type_of_product__c</fullName>
    <label>Type of product</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transportation__c/fields/Urgent_1_10__c.field-meta.xml
<CustomField>
    <fullName>Urgent_1_10__c</fullName>
    <label>Urgent (1-10)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateTransportation.cls
public class UpdateTransportation {
    @AuraEnabled
    public static Transportation__c getRecord(string recordId){
        Transportation__c trans = [SELECT id, Name, Companies__c, Companies__r.Name, Contact__c, Contact__r.Name, Destination_Pick_on_Map__c, Drivers__c,
        Drivers__r.Name, Price__c, Starting_Point_Pick_on_Map__c, State__c, Type_of_product__c, Urgent_1_10__c FROM Transportation__c WHERE id =: recordId LIMIT 1];
        return trans;
    }
    @AuraEnabled
    public static Transportation__c updateRecord(Transportation__c value){
        try {
            update value;
            return value;
        }
        catch (Exception e) {
            throw new AuraHandledException('Something went wrong when update record!!!');
        }
    }
}