force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Companies Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Drivers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Driver__c/fields/Companies__c.field-meta.xml
<CustomField>
    <fullName>Companies__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Companies</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>Drivers</relationshipLabel>
    <relationshipName>Drivers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transportation__c/Transportation__c.object-meta.xml
<CustomObject>
    <label>Transportation</label>
    <nameField>
        <label>Transportation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transportations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transportation__c/fields/Companies__c.field-meta.xml
<CustomField>
    <fullName>Companies__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Companies</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>Transportations</relationshipLabel>
    <relationshipName>Transportations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transportation__c/fields/Drivers__c.field-meta.xml
<CustomField>
    <fullName>Drivers__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Drivers</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Transportations</relationshipLabel>
    <relationshipName>Transportations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transportation__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>recieved</fullName>
                <default>true</default>
                <label>recieved</label>
            </value>
            <value>
                <fullName>processing</fullName>
            </value>
            <value>
                <fullName>delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transportation__c/fields/Type_of_product__c.field-meta.xml
<CustomField>
    <fullName>Type_of_product__c</fullName>
    <label>Type of product</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TransportationView.cls
public class TransportationView {
    /*apex method to fetch wrapper of list view*/ 
    @AuraEnabled
    public static list<listViewWrapper> listValues(){
 
        list<listViewWrapper> listtrans = new list<listViewWrapper>();
 
        for(Transportation__c tr : [SELECT id, Name, State__c, Companies__r.Name, Drivers__r.Name, Type_of_product__c FROM Transportation__c]){ 
            listViewWrapper trans = new listViewWrapper();
            trans.id = tr.id;
            trans.name = tr.Name;
            trans.state = tr.State__c;
            trans.company = tr.Companies__r.Name;
            trans.driver = tr.Drivers__r.Name;
            trans.product = tr.Type_of_product__c;
            listtrans.add(trans);
        }
        return listtrans; 
    }
 
    /*wrapper class to store listView details*/ 
    public class listViewWrapper{
        @AuraEnabled public string id{get;set;} 
        @AuraEnabled public string name{get;set;} 
        @AuraEnabled public string state{get;set;}
        @AuraEnabled public string company{get;set;}
        @AuraEnabled public string driver{get;set;}
        @AuraEnabled public string product{get;set;}
    }
}