force-app/main/default/objects/Transportation__c/Transportation__c.object-meta.xml
<CustomObject>
    <label>Transportation</label>
    <nameField>
        <label>Transportation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transportations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transportation__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>recieved</fullName>
                <default>true</default>
                <label>recieved</label>
            </value>
            <value>
                <fullName>processing</fullName>
            </value>
            <value>
                <fullName>delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TransportationBatch.cls
global class TransportationBatch implements Database.Batchable<sObject>{
    global Database.QueryLocator start(Database.BatchableContext bc){
        System.debug('a');
        return Database.getQueryLocator('SELECT Id, State__c, Closed__c FROM Transportation__c');
    }
    global void execute(Database.BatchableContext bc, List<Transportation__c> transportations){
        System.debug(transportations);
        for(Transportation__c trans : transportations){
            if(trans.State__c == 'delivered'){
                trans.Closed__c = true;
            }
        }
        update transportations;
    }
    global void finish(Database.BatchableContext bc){

    }
}