force-app/main/default/objects/Account/fields/Acc_Email__c.field-meta.xml
<CustomField>
    <fullName>Acc_Email__c</fullName>
    <label>Acc Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/QueueableApiUpdateCustomer.cls
public class QueueableApiUpdateCustomer implements Queueable, Database.AllowsCallouts {
    private List<Account> accounts;

    public QueueableApiUpdateCustomer(List<Account> acc) {
        this.accounts = acc;
    }

    public void execute(QueueableContext context) {
        for(Account acc : accounts){
            HttpRequestApiStripe.postCustomerToUpdate(acc.Name, acc.Acc_Email__c, acc.Stripe_Id__c);
        }
    }
}