force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Drivers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Transportation__c/Transportation__c.object-meta.xml
<CustomObject>
    <label>Transportation</label>
    <nameField>
        <label>Transportation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transportations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transportation__c/fields/Drivers__c.field-meta.xml
<CustomField>
    <fullName>Drivers__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Drivers</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Transportations</relationshipLabel>
    <relationshipName>Transportations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transportation__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>recieved</fullName>
                <default>true</default>
                <label>recieved</label>
            </value>
            <value>
                <fullName>processing</fullName>
            </value>
            <value>
                <fullName>delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestTransportationBatch.cls
@isTest
public class TestTransportationBatch {
    @TestSetup
    static void makeData(){
        List<Driver__c> drivers = new List<Driver__c>();
        for(Integer i=0; i<200; i++){
            Driver__c dr = new Driver__c();
            dr.Name = 'driver' + i;
            dr.Email__c='driver'+i+'@gmail.com';
            drivers.add(dr);
        }
        insert drivers;
        List<Driver__c> driver = new List<Driver__c>([SELECT Id FROM Driver__c]);
        List<Transportation__c> transport = new List<Transportation__c>();
        for(Integer i=0; i<200; i++){
            Transportation__c trans = new Transportation__c();
            trans.Name = 'Trans'+i;
            trans.Drivers__c = driver[i].Id;
            trans.State__c = 'delivered';
            transport.add(trans);
        }
        insert transport;
    }

    @isTest
    static void BatchTransportation(){
        TransportationBatch batch = new TransportationBatch();
        Database.executeBatch(batch);
    }
}